function [fitresult, gof] = createFit(time_axis, great_0_less_1_tor)
%CREATEFIT(TIME_AXIS,GREAT_0_LESS_1_TOR)
%  Create a fit.
%
%  Data for 'curve_torque_time' fit:
%      X Input : time_axis
%      Y Output: great_0_less_1_tor
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Nov-2019 11:06:49


%% Fit: 'curve_torque_time'.
[xData, yData] = prepareCurveData( time_axis, great_0_less_1_tor );

% Set up fittype and options.
ft = fittype( 'poly6' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'curve_torque_time' );
h = plot( fitresult, xData, yData );
legend( h, 'great_0_less_1_tor vs. time_axis', 'curve_torque_time', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'time_axis', 'Interpreter', 'none' );
ylabel( 'great_0_less_1_tor', 'Interpreter', 'none' );
grid on


